### ISSUE TITLE
please provide a valid uuid

### ISSUE THREAD

**Issue by riassmismans** [NamesJoeyWheeler/PearsonDL#3]
Whaty do i have to do?

> C:\Users\test\PearsonDL>python3 PearsonDL.py -i 49214 -p 1
> Please provide a valid UUID for this book's ID!

**Comment by NamesJoeyWheeler** [comment]
The UUID should contain 36 characters.
49214 is not a valid UUID, due to it being only 5 digits.

**Comment by NamesJoeyWheeler** [comment]
Since you have not answered in 10 days, I assume this means that the issue has been resolved.
Therefore, I will close this issue.

**Comment by riassmismans** [comment]
This is the link. I don't find the UUID
https://etext.pearson.com/eplayer/pdfbook?invoketype=et1&smsid=114745665&bookserver=1&scenario=1&platform=1027&pagenumber=4&bookid=49214&userid=&hsid=019089807ae89b9a5bcdf8639be10bc1&key=15911271201446381179102020
